# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1425, 914)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("\n"
".QPushButton:hover{ \n"
"border-color: red;\n"
"}\n"
".QPushButton{\n"
"background-color: white;\n"
" border-style: solid;\n"
" border-width:3px;\n"
"border-color: black;\n"
" border-radius:50px;\n"
" min-width:100px;\n"
" min-height:100px;\n"
"font-size:60pt;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuPage.sizePolicy().hasHeightForWidth())
        self.menuPage.setSizePolicy(sizePolicy)
        self.menuPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuPage.setStyleSheet("#menuPage{\n"
"border-image: url(:/Images/background.JPG) 0 0 0 0 stretch stretch;\n"
"background-position: center;\n"
"background-repeat: none;\n"
"}")
        self.menuPage.setObjectName("menuPage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menuPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_menuPage = QtWidgets.QVBoxLayout()
        self.verticalLayout_menuPage.setObjectName("verticalLayout_menuPage")
        self.horizontalLayout_menuTitle = QtWidgets.QHBoxLayout()
        self.horizontalLayout_menuTitle.setObjectName("horizontalLayout_menuTitle")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_menuTitle.addItem(spacerItem)
        self.labelMenu = QtWidgets.QLabel(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenu.sizePolicy().hasHeightForWidth())
        self.labelMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(96)
        self.labelMenu.setFont(font)
        self.labelMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelMenu.setStyleSheet("text-shadow: 5px 5px 0px #eb452b, \n"
"                  10px 10px 0px #efa032, \n"
"                  15px 15px 0px #46b59b, \n"
"                  20px 20px 0px #017e7f, \n"
"                  25px 25px 0px #052939, \n"
"                  30px 30px 0px #c11a2b, \n"
"                  35px 35px 0px #c11a2b, \n"
"                  40px 40px 0px #c11a2b, \n"
"                  45px 45px 0px #c11a2b;")
        self.labelMenu.setObjectName("labelMenu")
        self.horizontalLayout_menuTitle.addWidget(self.labelMenu)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_menuTitle.addItem(spacerItem1)
        self.verticalLayout_menuPage.addLayout(self.horizontalLayout_menuTitle)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem2)
        self.verticalLayout_buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_buttons.setObjectName("verticalLayout_buttons")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem3)
        self.pushButtonGame = QtWidgets.QPushButton(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGame.sizePolicy().hasHeightForWidth())
        self.pushButtonGame.setSizePolicy(sizePolicy)
        self.pushButtonGame.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonGame.setFont(font)
        self.pushButtonGame.setStyleSheet("")
        self.pushButtonGame.setObjectName("pushButtonGame")
        self.verticalLayout_buttons.addWidget(self.pushButtonGame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem4)
        self.pushButtonSettings = QtWidgets.QPushButton(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSettings.sizePolicy().hasHeightForWidth())
        self.pushButtonSettings.setSizePolicy(sizePolicy)
        self.pushButtonSettings.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonSettings.setFont(font)
        self.pushButtonSettings.setStyleSheet("")
        self.pushButtonSettings.setObjectName("pushButtonSettings")
        self.verticalLayout_buttons.addWidget(self.pushButtonSettings)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem5)
        self.pushButtonExit = QtWidgets.QPushButton(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExit.sizePolicy().hasHeightForWidth())
        self.pushButtonExit.setSizePolicy(sizePolicy)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_buttons.addWidget(self.pushButtonExit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem6)
        self.horizontalLayout_buttons.addLayout(self.verticalLayout_buttons)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem7)
        self.verticalLayout_menuPage.addLayout(self.horizontalLayout_buttons)
        self.horizontalLayout_3.addLayout(self.verticalLayout_menuPage)
        self.stackedWidget.addWidget(self.menuPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelMenu.setText(_translate("MainWindow", "Audio szachy"))
        self.pushButtonGame.setText(_translate("MainWindow", "Graj"))
        self.pushButtonSettings.setText(_translate("MainWindow", "Ustawienia"))
        self.pushButtonExit.setText(_translate("MainWindow", "Wyjście"))
from . import Images_rc
