# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menuUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(1267, 806)
        mainMenu.setStyleSheet(".QPushButton:hover{ \n"
"border-color: red;\n"
"}\n"
".QPushButton{\n"
"background-color: white;\n"
" border-style: solid;\n"
" border-width:3px;\n"
"border-color: black;\n"
" border-radius:50px;\n"
" min-width:100px;\n"
" min-height:100px;\n"
"font-size:60pt;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(mainMenu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_menuPage_2 = QtWidgets.QWidget(mainMenu)
        self.verticalLayout_menuPage_2.setStyleSheet(".QWidget{\n"
"border-image: url(:/Images/background.JPG) 0 0 0 0 stretch stretch;\n"
"background-position: center;\n"
"background-repeat: none;\n"
"}")
        self.verticalLayout_menuPage_2.setObjectName("verticalLayout_menuPage_2")
        self.verticalLayout_menuPage = QtWidgets.QVBoxLayout(self.verticalLayout_menuPage_2)
        self.verticalLayout_menuPage.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_menuPage.setSpacing(0)
        self.verticalLayout_menuPage.setObjectName("verticalLayout_menuPage")
        self.horizontalLayout_menuTitle = QtWidgets.QHBoxLayout()
        self.horizontalLayout_menuTitle.setObjectName("horizontalLayout_menuTitle")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_menuTitle.addItem(spacerItem)
        self.labelMenu2 = QtWidgets.QLabel(self.verticalLayout_menuPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenu2.sizePolicy().hasHeightForWidth())
        self.labelMenu2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(96)
        self.labelMenu2.setFont(font)
        self.labelMenu2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelMenu2.setStyleSheet("")
        self.labelMenu2.setObjectName("labelMenu2")
        self.horizontalLayout_menuTitle.addWidget(self.labelMenu2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_menuTitle.addItem(spacerItem1)
        self.verticalLayout_menuPage.addLayout(self.horizontalLayout_menuTitle)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem2)
        self.verticalLayout_buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_buttons.setObjectName("verticalLayout_buttons")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem3)
        self.pushButtonGame = QtWidgets.QPushButton(self.verticalLayout_menuPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGame.sizePolicy().hasHeightForWidth())
        self.pushButtonGame.setSizePolicy(sizePolicy)
        self.pushButtonGame.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonGame.setFont(font)
        self.pushButtonGame.setStyleSheet("")
        self.pushButtonGame.setObjectName("pushButtonGame")
        self.verticalLayout_buttons.addWidget(self.pushButtonGame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem4)
        self.pushButtonSettings = QtWidgets.QPushButton(self.verticalLayout_menuPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSettings.sizePolicy().hasHeightForWidth())
        self.pushButtonSettings.setSizePolicy(sizePolicy)
        self.pushButtonSettings.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonSettings.setFont(font)
        self.pushButtonSettings.setStyleSheet("")
        self.pushButtonSettings.setObjectName("pushButtonSettings")
        self.verticalLayout_buttons.addWidget(self.pushButtonSettings)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem5)
        self.pushButtonExit = QtWidgets.QPushButton(self.verticalLayout_menuPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExit.sizePolicy().hasHeightForWidth())
        self.pushButtonExit.setSizePolicy(sizePolicy)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(106, 106))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_buttons.addWidget(self.pushButtonExit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_buttons.addItem(spacerItem6)
        self.horizontalLayout_buttons.addLayout(self.verticalLayout_buttons)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem7)
        self.verticalLayout_menuPage.addLayout(self.horizontalLayout_buttons)
        self.gridLayout.addWidget(self.verticalLayout_menuPage_2, 0, 0, 1, 1)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Form"))
        self.labelMenu2.setText(_translate("mainMenu", "Audio szachy"))
        self.pushButtonGame.setText(_translate("mainMenu", "Graj"))
        self.pushButtonSettings.setText(_translate("mainMenu", "Ustawienia"))
        self.pushButtonExit.setText(_translate("mainMenu", "Wyjście"))
from . import Images_rc
